version: "3.8"
services:
  api:
    image: clockedwtc/calculations-api:latest
    container_name: api
    ports:
      - "3000:8080"
  client:
    build:
      context: .
      target: base
    container_name: client
    stdin_open: true
    tty: true
    depends_on:
      - api
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/app
