name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:21-alpine3.18
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test:coverage

      - name: Coverage Summary
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Build
        run: npm run build

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      # - name: Generate lcov test report
      #   run: npm run test:coverage-lcov
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}

      - name: Collect output artifacts
        run: |
          echo "# Sonar scan" >> $GITHUB_STEP_SUMMARY
          echo "https://sonarcloud.io/project/overview?id=clocked-app_client" >> $GITHUB_STEP_SUMMARY
